name: 'NuGet'

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      BUILD_CONFIG: 'Release'

    steps:
    # - name: Dump env
    #   run: env | sort
    # - name: Dump GitHub context
    #   env:
    #     GITHUB_CONTEXT: ${{ toJson(github) }}
    #   run: echo "$GITHUB_CONTEXT"
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Set VERSION variable from tag
      run: |
        assemblyversion=$(echo ${{ github.event.release.tag_name }} | cut -d- -f1 | cut -dv -f2)
        echo "ASSEMBLYVERSION=${assemblyversion}" >> $GITHUB_ENV
        version=$(echo ${{ github.event.release.tag_name }} | cut -dv -f2)
        echo "VERSION=${version}" >> $GITHUB_ENV        
    - name: Build
      working-directory: ./src
      run: dotnet build /p:AssemblyVersion=${ASSEMBLYVERSION} /p:Version=${VERSION}
    - name: Test
      working-directory: ./src
      run: dotnet test --no-build
    - name: Pack
      working-directory: ./src
      run: dotnet pack /p:Version=${VERSION} --no-build --output .
    - uses: actions/upload-artifact@v4
      if: success() || failure()
      with:
        name: nuget-artifact
        path: '**/*.nupkg'
        retention-days: 1