name: 'Test Report'
on:
  workflow_run:
    workflows: ['CI']
    types:
      - completed
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
    - name: Download test report file
      uses: actions/download-artifact@v4
      with:
        github-token: ${{ secrets.GH_DOWNLOAD_TOKEN }}
        pattern: test-results*
        run-id: ${{ github.event.workflow_run.id }}
    - name: Generate test report
      uses: dorny/test-reporter@v2
      with:
        #artifact: test-results
        name: dotNET Tests
        path: '**/*.trx'
        reporter: dotnet-trx
